"""xxx

Revision ID: 12f4a08b453f
Revises: 40e029f6f152
Create Date: 2017-06-12 22:35:54.792129

"""

# revision identifiers, used by Alembic.
revision = '12f4a08b453f'
down_revision = '40e029f6f152'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
