"""edit column

Revision ID: 131d4580b03d
Revises: 3b6bd6fc8585
Create Date: 2017-06-10 00:24:36.903354

"""

# revision identifiers, used by Alembic.
revision = '131d4580b03d'
down_revision = '3b6bd6fc8585'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('comment', sa.String(length=9999), nullable=True))
    op.add_column('hosts', sa.Column('projecttype', sa.String(length=64), nullable=True))
    op.drop_column('hosts', 'domaininfo')
    op.drop_column('hosts', 'manageuser')
    op.drop_column('hosts', 'managepasswd')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('managepasswd', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('hosts', sa.Column('manageuser', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('hosts', sa.Column('domaininfo', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('hosts', 'projecttype')
    op.drop_column('hosts', 'comment')
    ### end Alembic commands ###
