"""xxx

Revision ID: 38ce4d6004c9
Revises: 4a3b07ef9d23
Create Date: 2017-06-12 23:08:00.136096

"""

# revision identifiers, used by Alembic.
revision = '38ce4d6004c9'
down_revision = '4a3b07ef9d23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
