"""xxx

Revision ID: 40e029f6f152
Revises: 3439250036a7
Create Date: 2017-06-12 22:18:55.300020

"""

# revision identifiers, used by Alembic.
revision = '40e029f6f152'
down_revision = '3439250036a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
