"""xxx

Revision ID: 4a3b07ef9d23
Revises: 4b7b0d25bab9
Create Date: 2017-06-12 23:02:49.712059

"""

# revision identifiers, used by Alembic.
revision = '4a3b07ef9d23'
down_revision = '4b7b0d25bab9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
