"""xxx

Revision ID: 4b7b0d25bab9
Revises: e096917a080
Create Date: 2017-06-12 22:52:38.288403

"""

# revision identifiers, used by Alembic.
revision = '4b7b0d25bab9'
down_revision = 'e096917a080'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
