"""create

Revision ID: 84f21fd30b8
Revises: None
Create Date: 2017-06-11 22:20:06.889086

"""

# revision identifiers, used by Alembic.
revision = '84f21fd30b8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectname', sa.String(length=64), nullable=True),
    sa.Column('ipaddress', sa.String(length=64), nullable=False),
    sa.Column('ssh_user', sa.String(length=32), nullable=True),
    sa.Column('ssh_port', sa.SmallInteger(), nullable=True),
    sa.Column('ssh_passwd', sa.String(length=128), nullable=True),
    sa.Column('projecttype', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.String(length=9999), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hosts_ipaddress', 'hosts', ['ipaddress'], unique=True)
    op.create_index('ix_hosts_projectname', 'hosts', ['projectname'], unique=True)
    op.create_table('configinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelname', sa.String(length=64), nullable=True),
    sa.Column('modelpath', sa.String(length=64), nullable=True),
    sa.Column('modelcodepath', sa.String(length=64), nullable=True),
    sa.Column('modellogpath', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rl_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('roles', sa.SmallInteger(), nullable=True),
    sa.Column('role_status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_password_hash', 'users', ['password_hash'], unique=True)
    op.create_index('ix_users_rl_name', 'users', ['rl_name'], unique=True)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', 'users')
    op.drop_index('ix_users_rl_name', 'users')
    op.drop_index('ix_users_password_hash', 'users')
    op.drop_table('users')
    op.drop_table('configinfo')
    op.drop_index('ix_hosts_projectname', 'hosts')
    op.drop_index('ix_hosts_ipaddress', 'hosts')
    op.drop_table('hosts')
    ### end Alembic commands ###
