"""xxx

Revision ID: e096917a080
Revises: 12f4a08b453f
Create Date: 2017-06-12 22:49:51.803158

"""

# revision identifiers, used by Alembic.
revision = 'e096917a080'
down_revision = '12f4a08b453f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
