"""'1124'

Revision ID: 2c77f3486ee9
Revises: 57c659a7a24f
Create Date: 2016-11-24 21:19:21.947000

"""

# revision identifiers, used by Alembic.
revision = '2c77f3486ee9'
down_revision = '57c659a7a24f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
