"""'mesages'

Revision ID: 43537b86d3f4
Revises: 4c590b7e4ac0
Create Date: 2016-11-22 17:12:32.660000

"""

# revision identifiers, used by Alembic.
revision = '43537b86d3f4'
down_revision = '4c590b7e4ac0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
