"""'mesages'

Revision ID: 4c590b7e4ac0
Revises: None
Create Date: 2016-11-22 15:37:33.393000

"""

# revision identifiers, used by Alembic.
revision = '4c590b7e4ac0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=32), nullable=True),
    sa.Column('hostip', sa.String(length=32), nullable=True),
    sa.Column('hostport', sa.Integer(), nullable=True),
    sa.Column('hostuser', sa.String(length=64), nullable=True),
    sa.Column('hostpasspath', sa.String(length=64), nullable=True),
    sa.Column('dbhost', sa.String(length=64), nullable=True),
    sa.Column('dbname', sa.String(length=64), nullable=True),
    sa.Column('dbuser', sa.String(length=64), nullable=True),
    sa.Column('dbpass', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dbs_dbhost', 'dbs', ['dbhost'], unique=True)
    op.create_index('ix_dbs_hostname', 'dbs', ['hostname'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_password_hash', 'user', ['password_hash'], unique=True)
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_table('user_dbs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dbs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dbs_id'], ['dbs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_dbs')
    op.drop_index('ix_user_username', 'user')
    op.drop_index('ix_user_password_hash', 'user')
    op.drop_table('user')
    op.drop_index('ix_dbs_hostname', 'dbs')
    op.drop_index('ix_dbs_dbhost', 'dbs')
    op.drop_table('dbs')
    ### end Alembic commands ###
