"""'mesages'

Revision ID: 57c659a7a24f
Revises: 43537b86d3f4
Create Date: 2016-11-22 17:54:23.061000

"""

# revision identifiers, used by Alembic.
revision = '57c659a7a24f'
down_revision = '43537b86d3f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    ### end Alembic commands ###
